In [1]:
 import pandas as pd
# Create dataframe
df = pd.DataFrame({'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]})
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

# task : sales : double

In [2]:
df["Sales_double"]=df["Sales"]*2
df

Company   Person  Sales  Sales_double
0    GOOG      Sam    200           400
1    GOOG  Charlie    120           240
2    MSFT      Amy    340           680
3    MSFT  Vanessa    124           248
4      FB     Carl    243           486
5      FB    Sarah    350           700

# task: length of each company

In [3]:
l=[]
for i in df["Company"]:
    l.append(len(i))
l

[4, 4, 4, 4, 2, 2]

In [4]:
df["Company_length"]=l
df

Company   Person  Sales  Sales_double  Company_length
0    GOOG      Sam    200           400               4
1    GOOG  Charlie    120           240               4
2    MSFT      Amy    340           680               4
3    MSFT  Vanessa    124           248               4
4      FB     Carl    243           486               2
5      FB    Sarah    350           700               2

# apply

In [5]:
df["Company_len"]=df["Company"].apply(lambda x:len(x))

In [6]:
df

Company   Person  Sales  Sales_double  Company_length  Company_len
0    GOOG      Sam    200           400               4            4
1    GOOG  Charlie    120           240               4            4
2    MSFT      Amy    340           680               4            4
3    MSFT  Vanessa    124           248               4            4
4      FB     Carl    243           486               2            2
5      FB    Sarah    350           700               2            2

# task: first two alphabat of person name

In [7]:
df["Person_first"]=df["Person"].apply(lambda x:x[:2])

In [8]:
df

Company   Person  Sales  Sales_double  Company_length  Company_len  \
0    GOOG      Sam    200           400               4            4   
1    GOOG  Charlie    120           240               4            4   
2    MSFT      Amy    340           680               4            4   
3    MSFT  Vanessa    124           248               4            4   
4      FB     Carl    243           486               2            2   
5      FB    Sarah    350           700               2            2   

  Person_first  
0           Sa  
1           Ch  
2           Am  
3           Va  
4           Ca  
5           Sa

In [9]:
df["Person"]=df["Person"].apply(lambda x:"charles" if ((x=="Carl") | (x=="Charlie")) else x)
df

Company   Person  Sales  Sales_double  Company_length  Company_len  \
0    GOOG      Sam    200           400               4            4   
1    GOOG  charles    120           240               4            4   
2    MSFT      Amy    340           680               4            4   
3    MSFT  Vanessa    124           248               4            4   
4      FB  charles    243           486               2            2   
5      FB    Sarah    350           700               2            2   

  Person_first  
0           Sa  
1           Ch  
2           Am  
3           Va  
4           Ca  
5           Sa

In [10]:
df["Person1"]=df["Person"].apply(lambda x:x.swapcase())
df

Company   Person  Sales  Sales_double  Company_length  Company_len  \
0    GOOG      Sam    200           400               4            4   
1    GOOG  charles    120           240               4            4   
2    MSFT      Amy    340           680               4            4   
3    MSFT  Vanessa    124           248               4            4   
4      FB  charles    243           486               2            2   
5      FB    Sarah    350           700               2            2   

  Person_first  Person1  
0           Sa      sAM  
1           Ch  CHARLES  
2           Am      aMY  
3           Va  vANESSA  
4           Ca  CHARLES  
5           Sa    sARAH

In [11]:
df=pd.DataFrame({"names":["tushar","vipin","jai","pawan","mukul"],"weight":["76 kg","57.9 KG","80","56 k","66"]})
df

names   weight
0  tushar    76 kg
1   vipin  57.9 KG
2     jai       80
3   pawan     56 k
4   mukul       66

# string accessor

In [16]:
l=["ravi","pranav","uttkarsh",121,"dhruv","pinki"]
list(map(lambda x: x if x.startswith("p") else "",l))

AttributeError: 'int' object has no attribute 'startswith'

In [17]:
l=["ravi","pranav","uttkarsh",121,"dhruv","pinki"]
s=pd.Series(l)
s

0        ravi
1      pranav
2    uttkarsh
3         121
4       dhruv
5       pinki
dtype: object

In [18]:
s.str.startswith("p")

0    False
1     True
2    False
3      NaN
4    False
5     True
dtype: object

In [19]:
s.str.replace("pranav","Pranav")

0        ravi
1      Pranav
2    uttkarsh
3         NaN
4       dhruv
5       pinki
dtype: object

In [22]:
df=pd.read_csv("C:\\PRANAV\\Madrid Software\\Python\\data sets\\titanic\\train.csv")
df
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

# task : 

In [23]:
df["Name"].unique()

array(['Braund, Mr. Owen Harris',
       'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
       'Heikkinen, Miss. Laina',
       'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
       'Allen, Mr. William Henry', 'Moran, Mr. James',
       'McCarthy, Mr. Timothy J', 'Palsson, Master. Gosta Leonard',
       'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
       'Nasser, Mrs. Nicholas (Adele Achem)',
       'Sandstrom, Miss. Marguerite Rut', 'Bonnell, Miss. Elizabeth',
       'Saundercock, Mr. William Henry', 'Andersson, Mr. Anders Johan',
       'Vestrom, Miss. Hulda Amanda Adolfina',
       'Hewlett, Mrs. (Mary D Kingcome) ', 'Rice, Master. Eugene',
       'Williams, Mr. Charles Eugene',
       'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
       'Masselmani, Mrs. Fatima', 'Fynney, Mr. Joseph J',
       'Beesley, Mr. Lawrence', 'McGowan, Miss. Anna "Annie"',
       'Sloper, Mr. William Thompson', 'Palsson, Miss. Torborg Danira',
       'Asplund, Mrs. Carl Oscar 

In [24]:
df["Name"].str.split(",",expand=True)

0                                            1
0       Braund                              Mr. Owen Harris
1      Cumings   Mrs. John Bradley (Florence Briggs Thayer)
2    Heikkinen                                  Miss. Laina
3     Futrelle           Mrs. Jacques Heath (Lily May Peel)
4        Allen                            Mr. William Henry
..         ...                                          ...
886   Montvila                                  Rev. Juozas
887     Graham                         Miss. Margaret Edith
888   Johnston               Miss. Catherine Helen "Carrie"
889       Behr                              Mr. Karl Howell
890     Dooley                                  Mr. Patrick

[891 rows x 2 columns]

In [25]:
df[["first","last"]]=df["Name"].str.split(",",expand=True)
df.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked    first  \
0      0  A/5 21171   7.2500   NaN        S   Braund   
1      0   PC 17599  71.2833   C85        C  Cumings   

                                          last  
0                              Mr. Owen Harris  
1   Mrs. John Bradley (Florence Briggs Thayer)

In [26]:
df[["salutations","last name"]]=df["last"].str.split(n=1,expand=True)

In [27]:
df.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked    first  \
0      0  A/5 21171   7.2500   NaN        S   Braund   
1      0   PC 17599  71.2833   C85        C  Cumings   

                                          last salutations  \
0                              Mr. Owen Harris         Mr.   
1   Mrs. John Bradley (Florence Briggs Thayer)        Mrs.   

                               last name  
0                            Owen Harris  
1  John Bradley (Florence Briggs Thayer)

In [28]:
df["salutations"].unique()

array(['Mr.', 'Mrs.', 'Miss.', 'Master.', 'Don.', 'Rev.', 'Dr.', 'Mme.',
       'Ms.', 'Major.', 'Lady.', 'Sir.', 'Mlle.', 'Col.', 'Capt.', 'the',
       'Jonkheer.'], dtype=object)

In [29]:
df["Cabin"].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [30]:
df["Cabin"]=df["Cabin"].fillna(df["Cabin"].mode()[0])

In [31]:
df["Cabin_grp"]=df["Cabin"].apply(lambda x:x[0])

In [32]:
df.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare    Cabin Embarked    first  \
0      0  A/5 21171   7.2500  B96 B98        S   Braund   
1      0   PC 17599  71.2833      C85        C  Cumings   

                                          last salutations  \
0                              Mr. Owen Harris         Mr.   
1   Mrs. John Bradley (Florence Briggs Thayer)        Mrs.   

                               last name Cabin_grp  
0                            Owen Harris         B  
1  John Bradley (Florence Briggs Thayer)         C

In [33]:
df["Cabin_grp"].value_counts()

Cabin_grp
B    734
C     59
D     33
E     32
A     15
F     13
G      4
T      1
Name: count, dtype: int64

In [34]:
df=pd.DataFrame({"names":["tushar","vipin","jai","pawan","mukul"],"weight":["76 kg","57.9 KG","80","56 k","66"]})
df

names   weight
0  tushar    76 kg
1   vipin  57.9 KG
2     jai       80
3   pawan     56 k
4   mukul       66

In [35]:
df["weight"].dtypes

dtype('O')

In [36]:
df["weight"].unique()

array(['76 kg', '57.9 KG', '80', '56 k', '66'], dtype=object)

In [37]:
df["weight1"]=df["weight"].str.split(expand=True)[0]

In [38]:
df

names   weight weight1
0  tushar    76 kg      76
1   vipin  57.9 KG    57.9
2     jai       80      80
3   pawan     56 k      56
4   mukul       66      66

In [39]:
df["weight1"]=df["weight1"].astype(float)

In [40]:
df["weight1"].mean()

67.17999999999999

In [41]:
df=pd.DataFrame({"NAMES":["balmeet kaur","jai singh","aviraj_singh","leena ,oberoi","kawal kaur"],"empid":["123@madrid1","23@Madrid","900#empid","185_id","1234"]})
df

NAMES        empid
0   balmeet kaur  123@madrid1
1      jai singh    23@Madrid
2   aviraj_singh    900#empid
3  leena ,oberoi       185_id
4     kawal kaur         1234

In [42]:
df["empid"].unique()

array(['123@madrid1', '23@Madrid', '900#empid', '185_id', '1234'],
      dtype=object)

In [43]:
l=[]
for i in df["empid"]:
    if type(i)==str:
        ss=i[:4]
        d=""
        for ch in ss:
            if ch.isdigit():
                d=d+ch
        l.append(d)
    else:
        l.append(i)
l
        

['123', '23', '900', '185', '1234']

In [44]:
df["emp_id"]=l
df

NAMES        empid emp_id
0   balmeet kaur  123@madrid1    123
1      jai singh    23@Madrid     23
2   aviraj_singh    900#empid    900
3  leena ,oberoi       185_id    185
4     kawal kaur         1234   1234

In [45]:
df["NAMES"].str.replace("_"," ").str.replace(",","").str.split(expand=True)

0       1
0  balmeet    kaur
1      jai   singh
2   aviraj   singh
3    leena  oberoi
4    kawal    kaur

In [46]:
df=pd.DataFrame({"course_code": ["1","2","3","2","1","2","3"],"Names":["a","c","d","i","e","f","g"],"score":[35,45,25,36,47,38,30]})
df

course_code Names  score
0           1     a     35
1           2     c     45
2           3     d     25
3           2     i     36
4           1     e     47
5           2     f     38
6           3     g     30

In [47]:
df.sort_values(by="score",ascending=False)["Names"].head(2).values

array(['e', 'c'], dtype=object)

In [48]:
df.sort_values(by=["course_code","Names"],ascending=False)

course_code Names  score
6           3     g     30
2           3     d     25
3           2     i     36
5           2     f     38
1           2     c     45
4           1     e     47
0           1     a     35

In [49]:
import numpy as np
df=pd.DataFrame({'Age': np.random.randint(1, 100, 10)})
df

Age
0   43
1   83
2   50
3   84
4   30
5   15
6   16
7   63
8   87
9   70

In [50]:
df["age_cat"]=pd.cut(df["Age"],bins=[0,20,40,60,80],labels=["kids","adult","old","very old"])
df

Age   age_cat
0   43       old
1   83       NaN
2   50       old
3   84       NaN
4   30     adult
5   15      kids
6   16      kids
7   63  very old
8   87       NaN
9   70  very old

# traversal in df

In [51]:
df = pd.DataFrame([[1,2,3],[4,5,8],[34,56,78]],columns = ['col1','col2','col3'])  
df

col1  col2  col3
0     1     2     3
1     4     5     8
2    34    56    78

In [52]:
for i in df.iterrows():
    print(i)
    print("\n")

(0, col1    1
col2    2
col3    3
Name: 0, dtype: int64)


(1, col1    4
col2    5
col3    8
Name: 1, dtype: int64)


(2, col1    34
col2    56
col3    78
Name: 2, dtype: int64)




In [53]:
for i in df.iterrows():
    print("row number  ",i[0])
    print("data\n",i[1].values)
    print("\n")

row number   0
data
 [1 2 3]


row number   1
data
 [4 5 8]


row number   2
data
 [34 56 78]




In [54]:
for i in df.iterrows():
    print("row number  ",i[0])
    print("data\n",i[1]["col2"])
    print("\n")

row number   0
data
 2


row number   1
data
 5


row number   2
data
 56


